### ISSUE TITLE
Do we really want to be resolving DNS on every lookup?

### ISSUE THREAD

**Issue by 5731la** [LogoiLab/frwl#13]
I can think of reasons we would and would not want to do that, on one hand its nice to be able to look at an ip and know what it is but on the other hand its more data to store and compress...

**Comment by mrcbax** [comment]
There is some juicy info in the dns names like `us-embassy-mts-1gb-vl203-border-gi0-0-0.aas.ru` That would be massively slow operations to whois from IPs in bulk later for me.

**Comment by 5731la** [comment]
Yeah, that what I thought, as long as you're ok with the (possibly significant) data you'll have to deal with then its ok I guess
