### ISSUE TITLE
File orgainization

### ISSUE THREAD

**Issue by 5731la** [LogoiLab/frwl#14]
I have over 340k tarballs and I've been running for a day, im willing to set up file trees (I was thinking IP>year> month> day> hour) but I need the thumbs up first.

**Comment by mrcbax** [comment]
That will make it a little harder to stream process but hey I can sort it out later I'm already expecting to have to individually process everyone's submissions into a common format.

**Comment by 5731la** [comment]
closing as #17 is a solution to this and holds this discussion
