### ISSUE TITLE
Errors on line 64 and 95

### ISSUE THREAD

**Issue by mrcbax** [LogoiLab/frwl#20]
currently `ping_russia.sh` has the following non-critical errors (at least on archlinux):
```
line 64: warning command substitution: ignored null-byte in input.
line 95: [: too many arguments
```

I think line 64 is coming from a null-byte in `servers.txt`
I have no clue about line 95.

**Comment by mrcbax** [comment]
Any ideas @morrowc @Colseph @ConnorMcF?

**Comment by morrowc** [comment]
sure, I'll have a look.

**Comment by Colseph** [comment]
line 95 originates from line 92.
`du` returns all 47K folders
a simple fix would be adding the `-s` flag
` SIZE=$(du -sB 50M "${WORKING_DIR}" | cut ...`

**Comment by morrowc** [comment]
yup, and the line64 should be fixed in the next pr (running test to see that it's working as expected)

**Comment by mrcbax** [comment]
while we're at it can someone explain why we need 47K folders? btrfs no likey too much.

**Comment by morrowc** [comment]
how is btrfs being unhappy exactly?
(I reduced it to 2 levels)

**Comment by Colseph** [comment]
see issue [#4](https://github.com/LogoiLab/frwl/issues/4) @LogoiLab

**Comment by Colseph** [comment]
actually itll only make 47K folders the initial run. they'll get removed when the first tar command runs then wont be re-created as `_checkPath` is not in the loop

**Comment by mrcbax** [comment]
It takes about 4 seconds to provide anything related to IO. ls, du, etc take about 4 seconds to return.

**Comment by morrowc** [comment]
hrm also fixed that. (checkpath)

**Comment by morrowc** [comment]
I guess brtfs isn't the next best replacement to reiserfs? :)

**Comment by mrcbax** [comment]
yea 2 levels deep is fine. also, had to revert that last merge. see Pull Request #24
