### ISSUE TITLE
Docker image is out of date.

### ISSUE THREAD

**Issue by mrcbax** [LogoiLab/frwl#21]
I'm not very docker fluent and @danukefl is the owner of the repo on docker hub.

**Comment by 5731la** [comment]
I'm also not fluent in docker, but to fix this for the future it should try to compile directly from the git instead of hoping that someone updates it

**Comment by danukefl** [comment]
Yeah, I haven't had time to sit back down and update my fork. @LogoiLab should be able to setup his own Docker Hub account to link to the repo, it is setup for CI so it will create new builds automatically on commits. The only thing that should be updated for the script is whether IPs will still be pulled in automatically, or passed in through the environment variable. I know someone else was working on the Dockerfile in a fork. I'll be able to dig in more this weekend.

**Comment by danukefl** [comment]
And also modify the script to support being ran standalone or in the docker image itself, which I believe was also part of the fork from LukeCroteau.

**Comment by mrcbax** [comment]
Got it up on my account added build integration. should be good to go for when you're ready @danukefl 

https://cloud.docker.com/repository/docker/logoilab/frwl/general

Build failing. I'm assuming your fork has some special stuff.

**Comment by danukefl** [comment]
I just created the pull request. The build was failing since the Dockerfile wasn't in the root. The folder has been removed since the iamge runs off the same script now.

**Comment by mrcbax** [comment]
Cool all is good then
